# Generated by Django 2.2.5 on 2019-09-30 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_optedcourse'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='response',
            unique_together={('student_id', 'test_id', 'question_id')},
        ),
    ]
