# Generated by Django 2.2.5 on 2019-09-30 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_auto_20190930_1304'),
    ]

    operations = [
        migrations.RenameField(
            model_name='response',
            old_name='Response',
            new_name='response',
        ),
        migrations.AddField(
            model_name='response',
            name='score',
            field=models.IntegerField(choices=[(1, 1), (1, 1)], default=1),
        ),
    ]
