# Generated by Django 2.2.5 on 2019-10-13 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_auto_20190930_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='student_name',
            field=models.CharField(default='', max_length=32),
        ),
    ]
