# Generated by Django 2.2.5 on 2019-10-31 12:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0015_auto_20191030_0912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 10, 31, 12, 10, 35, 4043, tzinfo=utc)),
        ),
    ]
