# Generated by Django 2.2.5 on 2019-11-01 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0019_auto_20191031_2247'),
    ]

    operations = [
        migrations.AddField(
            model_name='totalscore',
            name='course_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='webapp.Course'),
        ),
    ]
