# Generated by Django 2.2.5 on 2019-11-01 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0020_totalscore_course_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='totalscore',
            name='course_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.Course'),
        ),
    ]
