# Generated by Django 2.2.6 on 2019-11-06 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0021_auto_20191101_1827'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='totalscore',
            name='course_id',
        ),
    ]
