# Generated by Django 2.2.7 on 2019-12-06 10:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0022_remove_totalscore_course_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='totalscore',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 12, 6, 10, 41, 24, 63335, tzinfo=utc)),
        ),
    ]
